config/routes.rb
Rails.application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'

  devise_for :users

  root "locations#index"

  resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :destroy, :edit, :update]
    resources :location_images, only: [:create, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index]
    resources :locations, only: [:update]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authorize!

  def edit
    @location = Location.find(params[:location_id])
    @review = Review.find(params[:id])
    authenticate_review(@review)
  end

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(params[:review].permit(:description, :spo_rating, :sce_rating, :exp_rating))
      flash[:notice] = "Review edited"
      redirect_to parent
    else
      flash[:notice] = "Review update failed"
      @location = parent
      @errors = @review.errors.full_messages
      render "reviews/edit"
    end
  end

  def new
    @location = Location.find(params[:location_id])
    @review = Review.new
  end

  def create
    @location_id = params[:location_id]
    @location = Location.find(params[:location_id])
    @review = Review.new(review_params)
    @review.location_id = @location_id
    @review.user = current_user

    if @review.save
      flash[:notice] = "Review created"
      redirect_to location_path(@location.id)
    else
      flash[:notice] = "Please fill out form correctly"
      @errors = @review.errors.full_messages
      render "reviews/new"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    return unless authenticate_review(@review)
    @location = @review.location
    @review.destroy
    flash[:notice] = "Review deleted"
    redirect_to location_path(@location)
  end

  private

  def parent
    @location ||= Location.find(params[:location_id])
  end

  def review_params
    params.require(:review).permit(:description, :spo_rating, :sce_rating, :exp_rating)
  end
end

app/views/reviews/_show.html.erb
<% if @reviews == [] %>
  <h4> No Reviews Yet </h4>
<% else %>
  <h4> REVIEWS: </h4>
  <% @reviews.each do |review| %>
    <div><h5> <%= review.description %></h5></div>
    <div><h6> by <%= review.user.username %></h6><div>
    <table>
      <tr>
        <th><u>Catagory</u></th>
        <th><u>Score</u></th>
      </tr>
      <tr>
        <td>Spookiness</td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= review.spo_rating %></td>
      </tr>
      <tr>
        <td>Scenery</td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= review.sce_rating %></td>
      </tr>
      <tr>
        <td>Exploration</td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= review.exp_rating %></td>
      </tr>
    </table>
    <h6><% if @user && (@user == review.user || @user.role == "admin") %>
      &nbsp;&nbsp;&nbsp;<%= link_to "Edit", edit_location_review_path(@location, review)%> &nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to "Delete",
      location_review_path(@location, review),
      method: :delete,
      action: :destroy%></h6>
    <% else %>
    <% end %>
    <div>&nbsp;</div>
  <% end %>
  <%= paginate @reviews %>
<% end %>

app/views/reviews/edit.html.erb
<!DOCTYPE html>
<html>

<h1> Update your review for <%= @location.name %> </h1>

<% if @review.errors.any? %>
  <br>
  <% @review.errors.full_messages.each do |error| %>
    <%= error %>
    <br>
  <% end %>
  <br>
<% end %>

<%= form_for [@location, @review] do |f| %>

<div>
  <%= f.label :review, class:"form_text" %>
  <%= f.text_area :description %>
</div>

<div>
  <%= f.label :Spookiness, class:"form_text" %>
  <%= f.select(:spo_rating, %w[1 2 3 4], {prompt: 'Spookiness'}) %>
</div>

<div>
  <%= f.label :Scenery, class:"form_text" %>
  <%= f.select(:sce_rating, %w[1 2 3 4], {prompt: 'Scenery'}) %>
</div>

<div>
  <%= f.label :Exploration, class:"form_text" %>
  <%= f.select(:exp_rating, %w[1 2 3 4], {prompt: 'Exploration'}) %>
</div>

<div>
  <%= f.submit "Update", class: "button alert expand" %>
</div>

<% end %>

</html>

app/views/reviews/new.html.erb
<!DOCTYPE html>
<html>

<h1> Write a Review for <%= @location.name %> </h1>

<% if @review.errors.any? %>
  <br>
  <% @review.errors.full_messages.each do |error| %>
    <%= error %>
    <br>
  <% end %>
  <br>
<% end %>

<%= form_for [@location, @review] do |f| %>

<div>
  <%= f.label :review, class:"form_text" %>
  <%= f.text_area :description %>
</div>

<div>
  <%= f.label :Spookiness, class:"form_text" %>
  <%= f.select(:spo_rating, %w[1 2 3 4], {prompt: 'Spookiness'}) %>
</div>

<div>
  <%= f.label :Scenery, class:"form_text" %>
  <%= f.select(:sce_rating, %w[1 2 3 4], {prompt: 'Scenery'}) %>
</div>

<div>
  <%= f.label :Exploration, class:"form_text" %>
  <%= f.select(:exp_rating, %w[1 2 3 4], {prompt: 'Exploration'}) %>
</div>

<div>
  <%= f.submit "Submit", class: "button alert expand"  %>
</div>

<% end %>

</html>