config/routes.rb
Rails.application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'

  devise_for :users

  root "locations#index"

  resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :destroy, :edit, :update]
    resources :location_images, only: [:create, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index]
    resources :locations, only: [:update]
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
  has_many :location_images

  validates :name, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: {
    minimum: 10,
    maximum: 300,
    tokenizer: lambda { |str| str.split(/\s+/) },
    too_short: "must have at least %{count} words",
    too_long: "must have at most %{count} words"
  }
  validates :state, presence: true
  validates :town, presence: true, length: { maximum: 30 }
  validates :size, presence: true
  validates :history, presence: true, length: {
    maximum: 300,
    tokenizer: lambda { |str| str.split(/\s+/) },
    too_long: "must have at most %{count} words"
  }
  validates :user_id, presence: true

  def self.search(query)
    where("name ilike :q or state ilike :q or town ilike :q", q: "%#{query}%")
  end

  paginates_per 10

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_action :authorize!

  def update
    @location = Location.find(params[:id])

    if @location.update(location_params)
      flash[:notice] = "Updated location."
      redirect_to location_path(@location)
    else
      flash[:alert] = "Could not update location."
      render "locations/show"
    end
  end
  
  private

  def location_params
    params.require(:location).permit(:endorsed)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authorize!, except: [:index, :show]

  def index
    @locations = Location.search(params[:search])
    @images = LocationImage.random(3)
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location].permit(:name, :description, :state, :town, :latitude, :longitude, :street, :size, :history, :endorsed))
      flash[:notice] = "Location updated"
      redirect_to parent
    else
      @location = parent
      flash[:notice] = "Please fill out form correctly"
      @errors = @location.errors.full_messages
      render "locations/edit"
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to root_path
  end

  def show
    @location = Location.find(params[:id])
    @reviews = @location.reviews.page(params[:page]).per(3)
    @user = current_user
    @image = LocationImage.new
    @spo_average = Review.where(location_id:params[:id]).average("spo_rating")
    @sce_average = Review.where(location_id:params[:id]).average("sce_rating")
    @exp_average = Review.where(location_id:params[:id]).average("exp_rating")
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    if @location.save
      flash[:notice] = "Location created"
      redirect_to location_path(@location)
    else
      flash[:notice] = "Please fill out form correctly"
      @errors = @location.errors.full_messages
      render "locations/new"
    end
  end

  private

  def parent
    @location ||= Location.find(params[:location_id])
  end


  def location_params
    params.require(:location).permit(:name, :description, :state, :town, :latitude, :longitude, :street, :size, :history, :private_land, :in_use)
  end

end

app/views/locations/_images.html.erb
<ul class="small-block-grid-3">
  <% @location.location_images.each do |location_image| %>
  <li><%= image_tag(location_image.image.url, alt: location_image.description) %><%= location_image.description %>
    <% if @user && (@user == location_image.user || @user.role == "admin") %><%= button_to "Delete image",
    location_location_image_path(@location, location_image),
    method: :delete,
    action: :destroy,
    class: "button alert tiny"%></li>
    <% end %>
  <% end %>
</ul>

<% if @user %>
  <div>&nbsp;</div>
  <div>Upload a photo of <%= @location.name %></div>
  <%= form_for [@location, @image] do |f| %>
    <div>
      <%= f.label :image, "Image Select", class:"image_select" %>
      <%= f.file_field :image %>
    </div>
    <div>
      <div class="small-4 columns">
        <%= f.label :description, "Image Description", class:"form_text" %>
        <%= f.text_field :description %>
      </div>
    </div>
    <br>
    <%= f.hidden_field :location_id, value: @location.id %>
    <%= f.submit "Add photo", class: "button alert tiny" %>
  <% end %>
  </div>
  <br>
  <div>&nbsp;</div>
<% else %>
  <div>&nbsp;</div>
  Sign in to add photos
  <div>&nbsp;</div>
<% end %>

app/views/locations/_map.html.erb
<% if @location.latitude && @location.longitude != "" %>
  <div class="col-2-3">
    <iframe
      width="600"
      height="450"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDRij-_j_RS6GJmGscH48MSyfdyYfyYRAs
        &q=<%=@location.latitude + "," + @location.longitude%>
        &zoom=18
        &maptype=satellite">
    </iframe>

  </div>

<div class="col-1-3">
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <h3>Latitude: <%= @location.latitude %></h3>
  <div>&nbsp;</div>
  <h3>Longitude: <%= @location.longitude %></h3>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
  <div>&nbsp;</div>
</div>

<% elsif @location.street != nil %>
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDRij-_j_RS6GJmGscH48MSyfdyYfyYRAs
    &q=<%=@location.street + "," + @location.town + "," + @location.state%>
    &zoom=18
    &maptype=satellite">
</iframe>
<br>
<% end %>

app/views/locations/edit.html.erb
<!DOCTYPE html>
<html>

<h1> Update <%= @location.name %> info</h1>

<% if @location.errors.any? %>
  <br>
  <% @location.errors.full_messages.each do |error| %>
    <%= error %>
    <br>
  <% end %>
  <br>
<% end %>

<%= form_for @location do |f| %>
  <div class="row">
  <div class="large-6 columns">
    <%= f.label :name, class: "form_text" %>
    <%= f.text_field :name, :placeholder => "Give a good spooky name to your discovered spot." %>
  </div>
</div>

<div>
  <%= f.label :description, class:"form_text" %>
  <%= f.text_area :description, :placeholder => "What's at the spot?  What is there to explore and see?  Any good scares?" %>
</div>

<div>
  <%= f.label :history, class:"form_text" %>
  <%= f.text_area :history, :placeholder => "Know any history about the spot?  If not leave as Unknown." %>
</div>

<div class="grid">

  <div class="map-1">
      <%= f.label :state, class:"form_text" %>
      <%= f.select :state, %w[AL MT AK NE AZ NV AR NH CA NJ CO NM CT NY DE NC FL ND GA OH HI OK ID OR IL PA IN RI IA SC KS SD KY TN LA TX ME UT MD VT MA VA MI WA MN WV MS WI MO WY]%>
  </div>

  <div class="map-2">
    <%= f.label :town, class:"form_text" %>
    <%= f.text_area :town %>
  </div>

  <div class="map-3">
    <%= f.label :street, class: "form_text" %>
    <%= f.text_area :street, :placeholder => "If applicable" %>
  </div>

  <div>&nbsp;</div>

  <div class="lat_long-1">
    <%= f.label "latitude", class: "form_text" %>
    <%= f.text_area :latitude, :placeholder => ""  %>
    <h6>Leave blank if unknown</h6>
  </div>

  <div class="lat_long-2">
    <%= f.label "longitude", class: "form_text" %>
    <%= f.text_area :longitude, :placeholder => ""  %>
    <h6>Leave blank if unknown</h6>
  </div>

</div>

<div class="row">
  <div class="small-2 columns">
    <%= f.label :size, class: "form_text" %>
    <%= f.select(:size, %w[Tiny Small Moderate Big Huge]) %>
  </div>
</div>

<div class="row">
  <div class="small-2 columns">
    <%= f.label :private_land, class: "form_text" %>
    <%= f.select(:private_land, ["Unknown", "Yes", "No"]) %>
  </div>
</div>

<div class="row">
  <div class="small-2 columns">
  <%= f.label :in_use, class: "form_text" %>
  <%= f.select(:in_use, ["Unknown", "Yes", "No"]) %>
  </div>
</div>
<div>&nbsp;</div>

<div>
  <%= f.submit "Update", class: "button alert expand" %>
</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>

<% end %>

</html>

app/views/locations/index.html.erb
<!DOCTYPE html>
<html>

<br>
<div align="center"> <p class = "banner"> Spooky Spots! </p> </div>
<div align="center"> <p class = "sub_banner"> Share Your Scares </p> </div>
<br>

<div>
  <ul <ul class="small-block-grid-3">
    <% @images.each do |image| %>
        <li><%= link_to image_tag(image.image.url), location_path(image.location_id) %></li>
    <% end %>
  </ul>
</div>

<div class="grid">
  <div class="col-2-3">
  <% @locations.each do |location| %>
  <h3><%= link_to location.name, location_path(location.id) %> - <%= location.town %>, <%= location.state %></h3>
  <% end %>
</div>
  <div class="col-1-3">
    <br>
    <div align="right", class="row">
      <div align="right">
        <%= form_tag(locations_path, method: "get") do %>
        <%= text_field_tag(:search, params[:search], placeholder: "Search Locations", class:"form_text") %>
        <%= submit_tag "Search", class: "button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

</html>

app/views/locations/new.html.erb
<!DOCTYPE html>
<html>

<h1> Create a New Spot </h1>

<% if @location.errors.any? %>
  <br>
  <% @location.errors.full_messages.each do |error| %>
    <%= error %>
    <br>
  <% end %>
  <br>
<% end %>


<%= form_for @location do |f| %>
  <div class="row">
  <div class="large-6 columns">
    <%= f.label :name, class: "form_text" %>
    <%= f.text_field :name, :placeholder => "Give a good spooky name to your discovered spot." %>
  </div>
</div>

<div>
  <%= f.label :description, class:"form_text" %>
  <%= f.text_area :description, :placeholder => "What's at the spot?  What is there to explore and see?  Any good scares?" %>
</div>

<div>
  <%= f.label :history, class:"form_text" %>
  <%= f.text_area :history, :placeholder => "Know any history about the spot?  If not leave as Unknown." %>
</div>

<div class="grid">

  <div class="map-1">
      <%= f.label :state, class:"form_text" %>
      <%= f.select :state, %w[AL MT AK NE AZ NV AR NH CA NJ CO NM CT NY DE NC FL ND GA OH HI OK ID OR IL PA IN RI IA SC KS SD KY TN LA TX ME UT MD VT MA VA MI WA MN WV MS WI MO WY]%>
  </div>

  <div class="map-2">
    <%= f.label :town, class:"form_text" %>
    <%= f.text_area :town %>
  </div>

  <div class="map-3">
    <%= f.label :street, class: "form_text" %>
    <%= f.text_area :street, :placeholder => "If applicable" %>
  </div>

  <div>&nbsp;</div>

  <div class="lat_long-1">
    <%= f.label "latitude", class: "form_text" %>
    <%= f.text_area :latitude, :placeholder => ""  %>
    <h6>Leave blank if unknown</h6>
  </div>

  <div class="lat_long-2">
    <%= f.label "longitude", class: "form_text" %>
    <%= f.text_area :longitude, :placeholder => ""  %>
    <h6>Leave blank if unknown</h6>
  </div>

</div>

<div class="row">
  <div class="small-2 columns">
    <%= f.label :size, class: "form_text" %>
    <%= f.select(:size, %w[Tiny Small Moderate Big Huge]) %>
  </div>
</div>

<div class="row">
  <div class="small-2 columns">
    <%= f.label :private_land, class: "form_text" %>
    <%= f.select(:private_land, ["Unknown", "Yes", "No"]) %>
  </div>
</div>

<div class="row">
  <div class="small-2 columns">
  <%= f.label :in_use, class: "form_text" %>
  <%= f.select(:in_use, ["Unknown", "Yes", "No"]) %>
  </div>
</div>
<div>&nbsp;</div>

<div>
  <%= f.submit "Submit", class: "button alert expand" %>
</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>

<% end %>

</html>

app/views/locations/show.html.erb
<!DOCTYPE html>
<html>

<h1><%= @location.name %></h1>

<% if @location.endorsed == true %>
  <h4> Endorsed By Spooky Spots </h4>
<% end %>
<div>&nbsp;</div>

<h6 align="right">Added by:&nbsp; <%= @location.user.username %> </h6>

<div class="grid">

  <div class="col-2-3">
    <div class="location">
      <h3><%= @location.description %></h3>
    </div>
  </div>

  <div class="col-1-3">
    <h4>State: </h4>
    <h5><%= @location.state %></h5>
    <h4>Town: </h4>
    <h5><%= @location.town %></h5>
    <% if (@location.street != nil) && (@location.street != "") %>
      <h4>Street: </h4>
      <h5><%= @location.street %> </h5>
    <% end %>
    <div>&nbsp;</div>
  </div>

  <div class="col-2-3">
    <h4>History: </h4>
    <h5><%= @location.history %></h5>
  </div>

  <div class="col-1-3">
    <h4>Size: </h4>
    <h5><%= @location.size %></h5>
    <h4>Private Land: </h4>
    <h5><%= @location.private_land %></h5>
    <h4>In Use: </h4>
    <h5><%= @location.in_use %></h5>
  </div>

  <%= render partial: "locations/map" %>

</div>

<div>&nbsp;</div>
<div>&nbsp;</div>

<% if @sce_average && @spo_average && @exp_average != nil %>
  <h4> Average Ratings: </h4>
  <h2 align="center">Spookiness: <%=@spo_average.round(1)%> &nbsp;&nbsp;&nbsp;&nbsp;  Scenery: <%=@sce_average.round(1)%> &nbsp;&nbsp;&nbsp;&nbsp; Exploration: <%=@exp_average.round(1)%> </h2>
<% else %>
  <h4> No Ratings Yet </h4>

<% end %>

<div>&nbsp;</div>

<% if @user && @user.role == "admin" %>
    <% if @location.endorsed == false %>
      <%= form_for [:admin, @location] do |f| %>
        <%= f.hidden_field :endorsed, value: true %>
        <%= f.submit "Endorse Location", class: "button success tiny" %>
      <% end %>
    <% elsif @location.endorsed == true %>
      <%= form_for [:admin, @location] do |f| %>
        <%= f.hidden_field :endorsed, value: false %>
        <%= f.submit "Un-Endorse Location", class: "button alert tiny" %>
      <% end %>
    <% end %>
<% end %>

<% if @user && (@user == @location.user || @user.role == "admin") %>
  <%= link_to "Edit Location", edit_location_path(@location), class: "button tiny" %>
<% end %>

<% if @user && @user.role == "admin" %>
  <%= button_to "Delete Location",
  location_path(@location),
  method: :delete,
  action: :destroy,
  class: "button alert tiny"%>
<% end %>

<div>&nbsp;</div>

<%= render partial: "locations/images" %>

<% if @user %>
<%= button_to "Review this Location", new_location_review_path(@location), method: "get", class: "button success tiny" %>
<% else %>
Sign in to review <%= @location.name %>
<div>&nbsp;</div>
<% end %>

<%= render partial: "reviews/show", locals: { location: @location } %>

<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>

</html>