config/routes.rb
Rails.application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'

  devise_for :users

  root "locations#index"

  resources :locations, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :destroy, :edit, :update]
    resources :location_images, only: [:create, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index]
    resources :locations, only: [:update]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Spooky Spots</title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="root_path"><%= link_to 'Spooky Spots', root_path %></a></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="active"><a href="#">
          <% if current_user %>
           <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
           <% else %>
           <%= link_to 'Sign In', new_user_session_path %>
           <% end %>
         </a></li>
        <li class="active"><a href="#">
         <% if current_user %>
           <%= link_to 'User Settings', edit_user_registration_path, method: :get %>
           <% else %>
           <%= link_to 'Sign Up', new_user_registration_path %>
           <% end %>
        </a></li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><a href="#">
          <% if current_user %>
          <%= link_to "Add New Spot", new_location_path(@location) %>
          <% end %> </a></li>
      </ul>

      <%- flash.each do |key, value| -%>
      <div class="ui message red">
        <center><%= value %></center>
      </div>
      <%- end -%>

    </section>
  </nav>
  <div class="row">
    <div class="small-12 columns">
      <%= yield %>
    </div>
  </div>



  <%= javascript_include_tag "application" %>
</body>
</html>